server:
  port: 8765

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutMilliseconds: 2000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/accounts
        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/api/v1/bills/**
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/api/v1/deposits/**
