logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutMilliseconds: 2000

eureka:
  instance:
    preferIpAddress: true
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/