server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.user_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true