server:
  port: 8083

spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.user_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/deposit_service_db
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true