spring:
  application:
    name: registry
  config:
    import: optional:configserver:http://localhost:8081
  cloud:
    config:
#      uri: http://localhost:8081
      fail-fast: true
      username: user
      password: admin

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    peer-node-read-timeout-ms: 100000
    waitTImeInMsWhenSyncEmpty: 0