spring:
  application:
    name: registry
  cloud:
    config:
      uri: http://localhost:8081
      fail-fast: true
      username: admin
      password: user

eureka:
  instance:
    preferIpAddress: true
    client:
      register-with-eureka: false
      fetch-registry: false
      server:
        waitTImeInMsWhenSyncEmpty: 0
    server:
      peer-node-read-timeout-ms: 100000