spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8081
  cloud:
    config:
      fail-fast: true
      username: user
      password: admin