spring:
  application:
    name: deposit-service
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    config:
      fail-fast: true
      username: user
      password: admin